/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRosePrakritiChatRouteImport } from './routes/api/public/rose-prakriti-chat'
import { Route as ApiPublicRoseCareersChatRouteImport } from './routes/api/public/rose-careers-chat'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicRazorpayVerifyRouteImport } from './routes/api/public/razorpay/verify'
import { Route as ApiPublicRazorpayCreateOrderRouteImport } from './routes/api/public/razorpay/create-order'
import { Route as ApiPublicDiscountsValidateRouteImport } from './routes/api/public/discounts/validate'
import { Route as ApiPublicAdminOrdersRouteImport } from './routes/api/public/admin/orders'
import { Route as ApiPublicAdminMeRouteImport } from './routes/api/public/admin/me'
import { Route as ApiPublicAdminLeadsRouteImport } from './routes/api/public/admin/leads'
import { Route as ApiPublicAdminDiscountsRouteImport } from './routes/api/public/admin/discounts'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRosePrakritiChatRoute =
  ApiPublicRosePrakritiChatRouteImport.update({
    id: '/api/public/rose-prakriti-chat',
    path: '/api/public/rose-prakriti-chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRoseCareersChatRoute =
  ApiPublicRoseCareersChatRouteImport.update({
    id: '/api/public/rose-careers-chat',
    path: '/api/public/rose-careers-chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayVerifyRoute = ApiPublicRazorpayVerifyRouteImport.update({
  id: '/api/public/razorpay/verify',
  path: '/api/public/razorpay/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayCreateOrderRoute =
  ApiPublicRazorpayCreateOrderRouteImport.update({
    id: '/api/public/razorpay/create-order',
    path: '/api/public/razorpay/create-order',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscountsValidateRoute =
  ApiPublicDiscountsValidateRouteImport.update({
    id: '/api/public/discounts/validate',
    path: '/api/public/discounts/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminOrdersRoute = ApiPublicAdminOrdersRouteImport.update({
  id: '/api/public/admin/orders',
  path: '/api/public/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminMeRoute = ApiPublicAdminMeRouteImport.update({
  id: '/api/public/admin/me',
  path: '/api/public/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminLeadsRoute = ApiPublicAdminLeadsRouteImport.update({
  id: '/api/public/admin/leads',
  path: '/api/public/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminDiscountsRoute = ApiPublicAdminDiscountsRouteImport.update({
  id: '/api/public/admin/discounts',
  path: '/api/public/admin/discounts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/rose-careers-chat': typeof ApiPublicRoseCareersChatRoute
  '/api/public/rose-prakriti-chat': typeof ApiPublicRosePrakritiChatRoute
  '/api/public/admin/discounts': typeof ApiPublicAdminDiscountsRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
  '/api/public/admin/me': typeof ApiPublicAdminMeRoute
  '/api/public/admin/orders': typeof ApiPublicAdminOrdersRoute
  '/api/public/discounts/validate': typeof ApiPublicDiscountsValidateRoute
  '/api/public/razorpay/create-order': typeof ApiPublicRazorpayCreateOrderRoute
  '/api/public/razorpay/verify': typeof ApiPublicRazorpayVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/rose-careers-chat': typeof ApiPublicRoseCareersChatRoute
  '/api/public/rose-prakriti-chat': typeof ApiPublicRosePrakritiChatRoute
  '/api/public/admin/discounts': typeof ApiPublicAdminDiscountsRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
  '/api/public/admin/me': typeof ApiPublicAdminMeRoute
  '/api/public/admin/orders': typeof ApiPublicAdminOrdersRoute
  '/api/public/discounts/validate': typeof ApiPublicDiscountsValidateRoute
  '/api/public/razorpay/create-order': typeof ApiPublicRazorpayCreateOrderRoute
  '/api/public/razorpay/verify': typeof ApiPublicRazorpayVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/rose-careers-chat': typeof ApiPublicRoseCareersChatRoute
  '/api/public/rose-prakriti-chat': typeof ApiPublicRosePrakritiChatRoute
  '/api/public/admin/discounts': typeof ApiPublicAdminDiscountsRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
  '/api/public/admin/me': typeof ApiPublicAdminMeRoute
  '/api/public/admin/orders': typeof ApiPublicAdminOrdersRoute
  '/api/public/discounts/validate': typeof ApiPublicDiscountsValidateRoute
  '/api/public/razorpay/create-order': typeof ApiPublicRazorpayCreateOrderRoute
  '/api/public/razorpay/verify': typeof ApiPublicRazorpayVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/register'
    | '/api/public/leads'
    | '/api/public/rose-careers-chat'
    | '/api/public/rose-prakriti-chat'
    | '/api/public/admin/discounts'
    | '/api/public/admin/leads'
    | '/api/public/admin/me'
    | '/api/public/admin/orders'
    | '/api/public/discounts/validate'
    | '/api/public/razorpay/create-order'
    | '/api/public/razorpay/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/register'
    | '/api/public/leads'
    | '/api/public/rose-careers-chat'
    | '/api/public/rose-prakriti-chat'
    | '/api/public/admin/discounts'
    | '/api/public/admin/leads'
    | '/api/public/admin/me'
    | '/api/public/admin/orders'
    | '/api/public/discounts/validate'
    | '/api/public/razorpay/create-order'
    | '/api/public/razorpay/verify'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/register'
    | '/api/public/leads'
    | '/api/public/rose-careers-chat'
    | '/api/public/rose-prakriti-chat'
    | '/api/public/admin/discounts'
    | '/api/public/admin/leads'
    | '/api/public/admin/me'
    | '/api/public/admin/orders'
    | '/api/public/discounts/validate'
    | '/api/public/razorpay/create-order'
    | '/api/public/razorpay/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicRoseCareersChatRoute: typeof ApiPublicRoseCareersChatRoute
  ApiPublicRosePrakritiChatRoute: typeof ApiPublicRosePrakritiChatRoute
  ApiPublicAdminDiscountsRoute: typeof ApiPublicAdminDiscountsRoute
  ApiPublicAdminLeadsRoute: typeof ApiPublicAdminLeadsRoute
  ApiPublicAdminMeRoute: typeof ApiPublicAdminMeRoute
  ApiPublicAdminOrdersRoute: typeof ApiPublicAdminOrdersRoute
  ApiPublicDiscountsValidateRoute: typeof ApiPublicDiscountsValidateRoute
  ApiPublicRazorpayCreateOrderRoute: typeof ApiPublicRazorpayCreateOrderRoute
  ApiPublicRazorpayVerifyRoute: typeof ApiPublicRazorpayVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rose-prakriti-chat': {
      id: '/api/public/rose-prakriti-chat'
      path: '/api/public/rose-prakriti-chat'
      fullPath: '/api/public/rose-prakriti-chat'
      preLoaderRoute: typeof ApiPublicRosePrakritiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rose-careers-chat': {
      id: '/api/public/rose-careers-chat'
      path: '/api/public/rose-careers-chat'
      fullPath: '/api/public/rose-careers-chat'
      preLoaderRoute: typeof ApiPublicRoseCareersChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay/verify': {
      id: '/api/public/razorpay/verify'
      path: '/api/public/razorpay/verify'
      fullPath: '/api/public/razorpay/verify'
      preLoaderRoute: typeof ApiPublicRazorpayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay/create-order': {
      id: '/api/public/razorpay/create-order'
      path: '/api/public/razorpay/create-order'
      fullPath: '/api/public/razorpay/create-order'
      preLoaderRoute: typeof ApiPublicRazorpayCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discounts/validate': {
      id: '/api/public/discounts/validate'
      path: '/api/public/discounts/validate'
      fullPath: '/api/public/discounts/validate'
      preLoaderRoute: typeof ApiPublicDiscountsValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/orders': {
      id: '/api/public/admin/orders'
      path: '/api/public/admin/orders'
      fullPath: '/api/public/admin/orders'
      preLoaderRoute: typeof ApiPublicAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/me': {
      id: '/api/public/admin/me'
      path: '/api/public/admin/me'
      fullPath: '/api/public/admin/me'
      preLoaderRoute: typeof ApiPublicAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/leads': {
      id: '/api/public/admin/leads'
      path: '/api/public/admin/leads'
      fullPath: '/api/public/admin/leads'
      preLoaderRoute: typeof ApiPublicAdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/discounts': {
      id: '/api/public/admin/discounts'
      path: '/api/public/admin/discounts'
      fullPath: '/api/public/admin/discounts'
      preLoaderRoute: typeof ApiPublicAdminDiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicRoseCareersChatRoute: ApiPublicRoseCareersChatRoute,
  ApiPublicRosePrakritiChatRoute: ApiPublicRosePrakritiChatRoute,
  ApiPublicAdminDiscountsRoute: ApiPublicAdminDiscountsRoute,
  ApiPublicAdminLeadsRoute: ApiPublicAdminLeadsRoute,
  ApiPublicAdminMeRoute: ApiPublicAdminMeRoute,
  ApiPublicAdminOrdersRoute: ApiPublicAdminOrdersRoute,
  ApiPublicDiscountsValidateRoute: ApiPublicDiscountsValidateRoute,
  ApiPublicRazorpayCreateOrderRoute: ApiPublicRazorpayCreateOrderRoute,
  ApiPublicRazorpayVerifyRoute: ApiPublicRazorpayVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
